[project]
name = "egents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "fastapi>=0.115.12",
    "fastmcp>=2.2.7",
    "fire>=0.7.0",
    "requests>=2.32.3",
    "uvicorn>=0.34.2",
]
