[project]
name = "listboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fire>=0.7.0",
    "pandas>=2.2.3",
    "pandera>=0.23.1",
    "tqdm>=4.67.1",
    "yt-dlp>=2025.3.25",
]
