[project]
name = "uhackathons_scraping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "llama-index-readers-web>=0.3.5",
    "nltk>=3.9.1",
]
