[project]
name = "uhackathons_tts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llvmlite==0.43",
    "parler-tts",
]

[tool.uv.sources]
parler-tts = { git = "https://github.com/huggingface/parler-tts.git"}
