[project]
name = "home_utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "audiblez>=0.4.9",
    "fastapi>=0.115.12",
    "fire>=0.7.0",
    "olmocr>=0.1.60",
    "openai>=1.78.1",
    "pip>=25.1.1",
]
